### ISSUE TITLE
Where do i find my AGENT_PUBLIC_DID_SEED, AGENT_ENDPOINT & AGENT_WALLET_KEY?

### ISSUE THREAD

**Issue by Squichell** [animo/animo-demo#132]

**Comment by Squichell** [comment]
I don't know what is meant by AGENT_PUBLIC_DID_SEED, AGENT_ENDPOINT & AGENT_WALLET_KEY, what I need for them and where I can find the appropriate variables.

**Comment by janrtvld** [comment]
Hi @Squichell! 

The public did is an identifier for a public entity/issuer. The public DID is based on the public did seed (like a public/private key pair). You can register a public did [here](http://test.bcovrin.vonx.io/).

The AGENT_WALLET_KEY is used for encrypting your wallet. For development you can use a simple non-secure key. 

The AGENT_ENDPOINT is an url where you can reach the agent. By default it sets up an Ngrok tunnel from your localhost so your agent is connected to the internet.

**Comment by janrtvld** [comment]
I think this can be closed. Please open another issue if you have any more questions or [join our discord](https://discord.gg/xmu2JHhQhT)!
