### ISSUE TITLE
Unable to run the demo locally on Ubuntu 20.04

### ISSUE THREAD

**Issue by ashish6913** [animo/animo-demo#171]
Hi,

I am trying to run the demo locally, however yarn install keeps throwing following error:

![image](https://user-images.githubusercontent.com/88108561/236907271-b80c15b5-efa0-476c-9274-afd7aaaf44bc.png)

Current setup:

Ubuntu 20.04
Node - 16.14.0
yarn - 1.22.19

Steps to reproduce:

- Clone the animo demo repo using https://github.com/animo/animo-demo.git
- Run yarn install in the root

Any help would be appreciated. Thanks! :)

**Comment by berendsliedrecht** [comment]
Hi! It looks like it cannot find libindy. This is a native library required for hosting the demo. 

Hopefully this guide can help you: https://aries.js.org/guides/getting-started/installation/nodejs

**Comment by ashish6913** [comment]
Hi @blu3beri, you are right and thanks for your response.
I was missing the libindy library but the AFJ documentation for linux didn't work out for me. However, the following Dockerfile commands solved my issue.

`RUN apt-get update -y && apt-get install -y software-properties-common apt-transport-https curl build-essential 

# libindy
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88
RUN add-apt-repository "deb https://repo.sovrin.org/sdk/deb bionic stable"

# nodejs
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash

# yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# install depdencies
RUN apt-get update -y && apt-get install -y --allow-unauthenticated \
    libindy \
    nodejs`
