### ISSUE TITLE
It is possible to get the same credential twice

### ISSUE THREAD

**Issue by TimoGlastra** [animo/animo-demo#25]
Submitted by an user from the cheqd telegram group. This is possible when you press "I didn't receive anything" but you did. If new credential offers are sent, we should delete (or make inactive) the old ones.

**Comment by janrtvld** [comment]
The old one is deleted, but we can't delete the notification in the wallet. When the user accepts the old one it prompts them with the message `this credential can not be accepted` (or something like that).

**Comment by TimoGlastra** [comment]
Yeah but I think you can still get it by accepting e.g. only one the issued credential (while two are offered), then press "I didn't receive anything" and you will get all credentials offered again.

**Comment by janrtvld** [comment]
Found the issue. It checks the credential state for `credential-issued`, but it should also check for state `done`.
