### ISSUE TITLE
Not able to run Demo on my local system 

### ISSUE THREAD

**Issue by SethiShivam** [animo/animo-demo#27]
Hi team ,

I am trying to run this demo on my local system. 
When I run  _**Yarn Dev**_ command

Command is running successfully but localhost:3000 is not returning anything (blank Front end)
Localhost:5000 is working fine . 
Could you please help me with this? 

Best Regards
Sethi Shivam

**Comment by janrtvld** [comment]
Hi there,

Are there any errors in the console of your browser? If so, could you post them here?

**Comment by SethiShivam** [comment]
Hi @janrtvld   Eveything is up , Agents are successfull created and  credential definitions are published .

 Please find the attached logs 
[Animo LOGS.txt](https://github.com/animo/animo-demo/files/7977572/Animo.LOGS.txt)

**Comment by janrtvld** [comment]
Could you also post the logs of your browser console? You can open the browser console by pressing Ctrl + Shift + J (Cmd + Option + J on Mac).

**Comment by SethiShivam** [comment]
![Screenshot from 2022-02-01 02-29-32](https://user-images.githubusercontent.com/29612154/151952575-80a5c2fc-8d2f-4acb-958c-f0df295c0b56.png)

**Comment by janrtvld** [comment]
Thanks!

It seems to be an issue with CRA and framer-motion explained [here](https://stackoverflow.com/questions/69769360/error-importing-framer-motion-v5-in-react-with-create-react-app). Could you try downgrading `framer-motion` in `client/package.json` to `4.1.17`?

**Comment by SethiShivam** [comment]
didn't work for me 

getting this 
![Screenshot from 2022-02-01 03-06-08](https://user-images.githubusercontent.com/29612154/151957668-ee630700-ef29-43df-82fb-708bae102e38.png)
NOTE:  I have not worked on Front-end ever

**Comment by janrtvld** [comment]
What node version are you using? Did you set the correct node version for the project with `nvm use`?

**Comment by SethiShivam** [comment]
I am using 16.13.2 . This comes with LTS

**Comment by SethiShivam** [comment]
Whats your system's configuration , I will try to have same system configuration : 

however I am using ubuntu 16.4 
Node 16.13.2 
Yarn 1.22.17

**Comment by janrtvld** [comment]
Can you try it with Node v16.8.0?

**Comment by SethiShivam** [comment]
![Screenshot from 2022-02-02 02-08-37](https://user-images.githubusercontent.com/29612154/152133797-3e519801-8f93-4b07-9215-8cade717b17e.png)
Same Issue , I tried with 16.8.0

**Comment by SethiShivam** [comment]
HI @janrtvld   I recloned the repo and ran the steps again and everything just worked fine . 

Thanks  but when I am using trinsic wallet and acting as a student and scanning QR for the certificate it is saying that Problem has been notified to the developers . 
I mean there is some prob coming at the time of receiving credentials and I did selected he BCovrin test network .

But for LISSI wallet its working fine . Check with your team if there is something wrong with Trinsic implementation
