### ISSUE TITLE
Getting 'Wasn't able to provision agent' error when trying to use the Trinsic Wallet Android Mobile App

### ISSUE THREAD

**Issue by jimezesinachi** [animo/animo-demo#79]
When trying to use the Trinsic Wallet, after selecting the region to connect, I get an error modal (popup) that says :Agent: Wasn't able to provision agent'. This continued happening even after several retries over different days and times. I figured it might have something to do with my location (Nigeria), but I figured you'd want to know.

**Comment by jimezesinachi** [comment]
![Screenshot_20220713-105018](https://user-images.githubusercontent.com/54069719/180412788-8855c630-898a-420f-a75f-46ed0110cc2d.png)

**Comment by jimezesinachi** [comment]
Here's my screenshot of the error popup, taken from my Android phone (Android 9.0)

**Comment by TimoGlastra** [comment]
This seems like an issue of the trinsic app and not something we can fix. Did you try different regions?

**Comment by jimezesinachi** [comment]
Yes. Same error message.

**Comment by janrtvld** [comment]
Have you tried the Lissi wallet? https://lissi.id/

**Comment by jimezesinachi** [comment]
Not yet. I'll check it out now. Thanks!

**Comment by jimezesinachi** [comment]
Apparently, the Lissi wallet app isn't available to download in my country.

**Comment by janrtvld** [comment]
Can this be closed @rapaktech ?

**Comment by jimezesinachi** [comment]
Yes! It's still an issue, but not with the demo. Ana said she reached out to them, but they don't seem to have fixed it yet.
