### ISSUE TITLE
Make a credential loading card

### ISSUE THREAD

**Issue by janrtvld** [animo/animo-demo#85]
Currently, when we issue a credential it shows a loading spinner when the request is being processed. Then, after the credential request is completed the credential card is shown with a loading spinner waiting for the user to accept it.

There is a small flicker in between:

https://user-images.githubusercontent.com/60812202/188142152-52bf9ca4-767a-4f65-9f5b-382ab278a600.mov

It would be nice if we have a placeholder credential card where the card indicates that the credential is loading (presumably with a pulsing effect). Like this: 

![image](https://user-images.githubusercontent.com/60812202/188142270-fddab55c-4e9e-4dec-a251-bdf480b827cf.png)

We should add an 'empty' credential card as a placeholder while the isLoading property is true.

**Comment by jimezesinachi** [comment]
I think we can close this now

**Comment by jimezesinachi** [comment]
@janrtvld
