### ISSUE TITLE
Toggle between oob and legacy invitations

### ISSUE THREAD

**Issue by TimoGlastra** [animo/animo-demo#94]
See https://github.com/animo/animo-demo/issues/87 for general context

1.  Add `useLegacyInvitations` boolean type to the `connectionSlice.ts`. True should be the default
2. add `setUseLegacyInvitations` to the reducers in the connections slice that sets wheter to use legacy invitations on the state.
3. Add option "Change Connection Invitation Type" with options "Legacy (RFC 0160)" and "Out Of Band" to the KBar.tsx file.
4. (ideally) add a way to see if we're using legacy / oob invitation from kbar ([timc1/kbar](https://github.com/timc1/kbar))
5. Whenever we create an invitation we should call `/oob/create-legacy-invitation` if legacy is enabled, and `/oob/create-invitation` otherwise. In both cases we should use the return invitaiton url and encode is as a QR (as is already happening)

**Comment by janrtvld** [comment]
For number 4: maybe a checkmark to indicate the type that is active? Like this:

![Group 2](https://user-images.githubusercontent.com/60812202/192703672-98e46396-7833-4480-9947-1f39ad8a3fa0.png)
